baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cool AI Tools'

theme = 'lightbi-hugo'

[author]                  # essential                     # 必需
  name = "coolai"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about/"